/*
    abl_help_randomizer.js
    ABL v26-style Direct_Parameter_Messaging randomizer

    Arguments: attribute:random or attribute:skip.
    Random values are generated by sending normalized rawfloat 0..1 to the
    parent patcher's native parameter-connected live.numbox. This delegates
    range/type mapping to Max/ABL, then mirrors the actual value into the
    Direct_Parameter_Messaging display and emits the exact attribute setter.
*/
autowatch=1;
inlets=1;
outlets=1;
var specs=[];
var raw=arrayfromargs(jsarguments).slice(1);
for (var i=0;i<raw.length;i++) {
    var s=String(raw[i]); var k=s.lastIndexOf(":");
    if (k<0) specs.push([s,"random"]); else specs.push([s.substring(0,k),s.substring(k+1)]);
}
function loadbang() { var t=new Task(sync,this); t.schedule(100); }
function bang() { randomize(); }
function anything() { if (messagename==="sync") sync(); }
function sync()
{
    for (var i=0;i<specs.length;i++) mirror(specs[i][0]);
}
function randomize()
{
    var parent=this.patcher.parentpatcher;
    if (!parent) return;
    for (var i=0;i<specs.length;i++) {
        var name=specs[i][0], mode=specs[i][1];
        if (mode!=="random") continue;
        var ctl=parent.getnamed("abl_param_"+safe(name));
        if (!ctl) continue;
        try { ctl.message("rawfloat",Math.random()); } catch(e) { continue; }
        var v=read(ctl);
        setdisplay(name,v);
        if (v!==null) outlet(0,name,v);
    }
}
function mirror(name)
{
    var parent=this.patcher.parentpatcher;
    if (!parent) return;
    var ctl=parent.getnamed("abl_param_"+safe(name));
    if (!ctl) return;
    setdisplay(name,read(ctl));
}
function read(box)
{
    try { var v=box.getvalueof(); if (v instanceof Array) v=v[0]; return v; }
    catch(e) { return null; }
}
function setdisplay(name,v)
{
    if (v===null) return;
    var b=this.patcher.getnamed("display_"+safe(name));
    if (!b) return;
    try { b.message("set",v); } catch(e) { try { b.setvalueof(v); } catch(e2) {} }
}
function safe(s) { return String(s).replace(/[^A-Za-z0-9_]/g,"_"); }
